# Generated by Django 6.0.3 on 2026-05-09 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_capacity_activity_created_at_activity_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '活动老师'), ('developer', '开发者')], default='student', max_length=20, verbose_name='用户角色'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='班级/部门'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='学号/工号'),
        ),
    ]
