# Generated by Django 6.0.3 on 2026-05-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_creator_profile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='checkin_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='签到码'),
        ),
        migrations.AddField(
            model_name='activity',
            name='checkin_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签到结束时间'),
        ),
        migrations.AddField(
            model_name='activity',
            name='checkin_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签到开始时间'),
        ),
        migrations.AddField(
            model_name='registration',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签到时间'),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_checked_in',
            field=models.BooleanField(default=False, verbose_name='是否已签到'),
        ),
    ]
