# Generated by Django 6.0.3 on 2026-05-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_checkin_code_activity_checkin_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='checkin_log',
            field=models.TextField(blank=True, help_text='记录签到操作的详细信息', null=True, verbose_name='签到日志'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='checkin_code',
            field=models.CharField(blank=True, help_text='6位签到码', max_length=6, null=True, verbose_name='签到码'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='is_checked_in',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已签到'),
        ),
    ]
